# Generated by Django 6.0.3 on 2026-07-28 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('events', '0002_event_max_guests_invitation_registration_participant_and_more'),
        ('sites', '0003_sitetheme_hero_heading_sitetheme_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmessage',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='events.invitation'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='events.eventoccurrence'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='events.registration'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddConstraint(
            model_name='outboundmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('site', 'dedupe_key'), name='communications_unique_dedupe_key_per_site'),
        ),
    ]
