# Generated by Django 6.0.3 on 2026-07-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundmessage',
            name='kind',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('confirmation', 'RSVP confirmation'), ('event_update', 'Event update'), ('cancellation', 'Cancellation'), ('reminder', 'Reminder'), ('ticket_receipt', 'Ticket receipt'), ('membership_receipt', 'Membership receipt')], max_length=30),
        ),
    ]
