# Generated by Django 6.0.3 on 2026-07-28 22:24

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_outboundmessage_kind'),
        ('contacts', '0002_member_membershipplan_membersubscription_and_more'),
        ('content', '0001_initial'),
        ('events', '0003_registration_payment_status'),
        ('sites', '0003_sitetheme_hero_heading_sitetheme_hero_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsUsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('reserved', 'Reserved'), ('accepted', 'Accepted by provider'), ('released', 'Released'), ('adjusted', 'Adjusted')], max_length=20)),
                ('segments', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UnsubscribeCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='is_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='sms_segments',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='unsubscribe_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='kind',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('confirmation', 'RSVP confirmation'), ('event_update', 'Event update'), ('cancellation', 'Cancellation'), ('reminder', 'Reminder'), ('ticket_receipt', 'Ticket receipt'), ('membership_receipt', 'Membership receipt'), ('campaign', 'Campaign'), ('campaign_test', 'Campaign test')], max_length=30),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('unsubscribed', 'Unsubscribed'), ('suppressed', 'Suppressed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('channel', models.CharField(choices=[('email', 'Email newsletter'), ('sms', 'SMS announcement')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('expanding', 'Building audience'), ('sending', 'Sending'), ('sent', 'Completed'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All eligible contacts'), ('members', 'Members'), ('non_members', 'Non-members'), ('event_invitees', 'Event invitees'), ('response', 'Event response status'), ('tag', 'Contact tag')], default='all', max_length=30)),
                ('response_filter', models.CharField(blank=True, max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('usage_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('eligible_count', models.PositiveIntegerField(default=0)),
                ('excluded_count', models.PositiveIntegerField(default=0)),
                ('estimated_segments', models.PositiveIntegerField(default=0)),
                ('sms_reserved_segments', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('audience_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='events.eventoccurrence')),
                ('audience_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='contacts.contacttag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('duplicated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='communications.campaign')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('source_blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeded_campaigns', to='content.blogpost')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='communications.campaign'),
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=320)),
                ('status', models.CharField(choices=[('excluded', 'Excluded'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('unsubscribed', 'Unsubscribed'), ('suppressed', 'Suppressed')], max_length=20)),
                ('exclusion_reason', models.CharField(blank=True, max_length=120)),
                ('segment_count', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=1000)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_deliveries', to='contacts.contact')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'ordering': ('contact__last_name', 'contact__first_name'),
            },
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='campaign_recipient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_message', to='communications.campaignrecipient'),
        ),
        migrations.CreateModel(
            name='ProviderCallbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-received_at',),
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='communications_unique_provider_callback')],
            },
        ),
        migrations.CreateModel(
            name='SmsAllowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('included_segments', models.PositiveIntegerField(default=0)),
                ('purchased_segments', models.PositiveIntegerField(default=0)),
                ('reserved_segments', models.PositiveIntegerField(default=0)),
                ('sent_segments', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'ordering': ('-period_start',),
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='sms_allowance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='communications.smsallowance'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='sms_allowance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='communications.smsallowance'),
        ),
        migrations.AddConstraint(
            model_name='outboundmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('channel', 'email'), ('recipient_email__gt', '')), models.Q(('channel', 'sms'), ('recipient_phone__gt', '')), _connector='OR'), name='communications_message_has_channel_address'),
        ),
        migrations.AddField(
            model_name='smsusageevent',
            name='allowance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='communications.smsallowance'),
        ),
        migrations.AddField(
            model_name='smsusageevent',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_usage', to='communications.campaign'),
        ),
        migrations.AddField(
            model_name='smsusageevent',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_usage', to='communications.campaignrecipient'),
        ),
        migrations.AddField(
            model_name='smsusageevent',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddField(
            model_name='unsubscribecapability',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unsubscribe_links', to='communications.campaign'),
        ),
        migrations.AddField(
            model_name='unsubscribecapability',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_links', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='unsubscribecapability',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddConstraint(
            model_name='campaignrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'contact'), name='communications_one_recipient_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='smsallowance',
            constraint=models.UniqueConstraint(fields=('site', 'period_start'), name='communications_one_sms_allowance_period'),
        ),
        migrations.AddConstraint(
            model_name='smsallowance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_segments__gte', 0)), name='communications_sms_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='smsallowance',
            constraint=models.CheckConstraint(condition=models.Q(('sent_segments__gte', 0)), name='communications_sms_sent_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='smsallowance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_segments__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('included_segments'), '+', models.F('purchased_segments')), '-', models.F('sent_segments')))), name='communications_sms_reserved_within_allowance'),
        ),
    ]
