# Generated by Django 6.0.3 on 2026-07-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_smsusageevent_unsubscribecapability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundmessage',
            name='kind',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('confirmation', 'RSVP confirmation'), ('event_update', 'Event update'), ('cancellation', 'Cancellation'), ('reminder', 'Reminder'), ('ticket_receipt', 'Ticket receipt'), ('membership_receipt', 'Membership receipt'), ('campaign', 'Campaign'), ('campaign_test', 'Campaign test'), ('review_request', 'Review request')], max_length=30),
        ),
    ]
