# Generated by Django 6.0.3 on 2026-07-28 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_member_membershipplan_membersubscription_and_more'),
        ('payments', '0001_initial'),
        ('sites', '0003_sitetheme_hero_heading_sitetheme_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_balance_transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_fee_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_net_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True)),
                ('amount_due_cents', models.PositiveIntegerField(default=0)),
                ('amount_paid_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed')], max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('member_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contacts.membersubscription')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
