# Generated by Django 6.0.3 on 2026-07-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_stripe_balance_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='last_sync_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='sync_failure_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
