# Generated by Django 6.0.7 on 2026-07-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_order_application_fee_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='refund_policy',
            field=models.TextField(blank=True, help_text="Leave blank to use your organization's default refund policy."),
        ),
    ]
