# Generated by Django 6.0.3 on 2026-07-28 19:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0003_sitetheme_hero_heading_sitetheme_hero_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('normalized_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('email_consent_status', models.CharField(choices=[('unknown', 'Unknown'), ('granted', 'Granted'), ('withdrawn', 'Withdrawn'), ('suppressed', 'Suppressed')], default='unknown', max_length=20)),
                ('sms_consent_status', models.CharField(choices=[('unknown', 'Unknown'), ('granted', 'Granted'), ('withdrawn', 'Withdrawn'), ('suppressed', 'Suppressed')], default='unknown', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('granted', 'Granted'), ('withdrawn', 'Withdrawn'), ('suppressed', 'Suppressed')], max_length=20)),
                ('source', models.CharField(max_length=80)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_history', to='contacts.contact')),
            ],
            options={
                'ordering': ('-recorded_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ContactTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contacttag')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(through='contacts.ContactTagAssignment', to='contacts.contacttag'),
        ),
        migrations.AddConstraint(
            model_name='contacttag',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='contacts_unique_tag_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='contacttagassignment',
            constraint=models.UniqueConstraint(fields=('contact', 'tag'), name='contacts_one_tag_assignment'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_email', ''), _negated=True), fields=('site', 'normalized_email'), name='contacts_unique_email_per_site'),
        ),
    ]
