# Generated by Django 6.0.7 on 2026-07-31 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mailing_address_line1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mailing_address_line2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mailing_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mailing_country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mailing_postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mailing_state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
