# Generated by Django 6.0.3 on 2026-07-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_max_guests_invitation_registration_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'No payment required'), ('pending', 'Payment required'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='not_required', max_length=20),
        ),
    ]
