# Generated by Django 6.0.7 on 2026-07-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_photos_and_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='event-albums/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='event-albums/%Y/%m/', width_field='image_width'),
        ),
    ]
