# Generated by Django 6.0.7 on 2026-08-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_photo_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoccurrence',
            name='canceled_by_event',
            field=models.BooleanField(default=False),
        ),
    ]
