# Generated by Django 6.0.3 on 2026-07-28 23:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_sitedeletionrequest_supportaccessgrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('observed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
