# Generated by Django 6.0.3 on 2026-07-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='platformsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('trial_ends_at__gt', models.F('trial_started_at'))), name='subscriptions_trial_end_after_start'),
        ),
    ]
