# Generated by Django 6.0.3 on 2026-07-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_platformsubscription_subscriptions_trial_end_after_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsubscription',
            name='billing_interval',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10),
        ),
    ]
