# Generated by Django 6.0.7 on 2026-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_platformsubscription_billing_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsubscription",
            name="last_stripe_event_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
