# Generated by Django 6.0.7 on 2026-07-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_platformsubscription_last_stripe_event_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsubscription',
            name='last_stripe_event_created_at',
        ),
    ]
