import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies=[('workspace','0001_initial'),('contacts','0002_member_membershipplan_membersubscription_and_more'),('events','0003_registration_payment_status'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='Sponsor',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=180)),('contact_name',models.CharField(blank=True,max_length=180)),('email',models.EmailField(blank=True,max_length=254)),('phone',models.CharField(blank=True,max_length=30)),('website',models.URLField(blank=True)),('logo',models.ImageField(blank=True,upload_to='sponsor-logos/%Y/%m/')),('status',models.CharField(choices=[('prospect','Prospect'),('active','Active'),('inactive','Inactive')],db_index=True,default='prospect',max_length=20)),('notes',models.TextField(blank=True)),('site',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='sites.site'))],options={'ordering':('name',)}),
      migrations.CreateModel(name='VolunteerProfile',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('status',models.CharField(choices=[('prospect','Prospect'),('active','Active'),('inactive','Inactive')],db_index=True,default='active',max_length=20)),('skills',models.TextField(blank=True,help_text='Comma-separated skills or qualifications.')),('availability',models.TextField(blank=True)),('emergency_contact',models.CharField(blank=True,max_length=180)),('emergency_phone',models.CharField(blank=True,max_length=30)),('background_check_expires_on',models.DateField(blank=True,null=True)),('notes',models.TextField(blank=True)),('contact',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='volunteer_profile',to='contacts.contact')),('site',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='sites.site'))],options={'ordering':('contact__last_name','contact__first_name')}),
      migrations.CreateModel(name='VolunteerShift',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('title',models.CharField(max_length=180)),('starts_at',models.DateTimeField()),('ends_at',models.DateTimeField()),('location',models.CharField(blank=True,max_length=180)),('capacity',models.PositiveSmallIntegerField(default=1)),('instructions',models.TextField(blank=True)),('event',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='volunteer_shifts',to='events.event')),('site',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='sites.site'))],options={'ordering':('starts_at','title')}),
      migrations.CreateModel(name='Sponsorship',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('level',models.CharField(blank=True,max_length=100)),('amount_cents',models.PositiveIntegerField(default=0)),('status',models.CharField(choices=[('proposed','Proposed'),('committed','Committed'),('invoiced','Invoiced'),('paid','Paid'),('canceled','Canceled')],db_index=True,default='proposed',max_length=20)),('starts_on',models.DateField(blank=True,null=True)),('ends_on',models.DateField(blank=True,null=True)),('benefits',models.TextField(blank=True)),('invoice_reference',models.CharField(blank=True,max_length=120)),('event',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='sponsorships',to='events.event')),('site',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='sites.site')),('sponsor',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='sponsorships',to='workspace.sponsor'))],options={'ordering':('-created_at',)}),
      migrations.CreateModel(name='VolunteerAssignment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(choices=[('assigned','Assigned'),('confirmed','Confirmed'),('completed','Completed'),('no_show','No show'),('canceled','Canceled')],db_index=True,default='assigned',max_length=20)),('notes',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('shift',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='assignments',to='workspace.volunteershift')),('volunteer',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='assignments',to='workspace.volunteerprofile'))],options={'ordering':('shift__starts_at','volunteer__contact__last_name')}),
      migrations.CreateModel(name='VolunteerHourEntry',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('service_date',models.DateField()),('hours',models.DecimalField(decimal_places=2,max_digits=6)),('description',models.CharField(blank=True,max_length=220)),('approved_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='approved_volunteer_hours',to=settings.AUTH_USER_MODEL)),('assignment',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='hour_entries',to='workspace.volunteerassignment')),('site',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='sites.site')),('volunteer',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='hour_entries',to='workspace.volunteerprofile'))],options={'ordering':('-service_date','-created_at')}),
      migrations.AddConstraint(model_name='volunteerassignment',constraint=models.UniqueConstraint(fields=('shift','volunteer'),name='workspace_one_volunteer_per_shift')),
    ]
