# Generated by Django 6.0.7 on 2026-07-30 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_sitetheme_brand_colors'),
        ('workspace', '0005_ai_content_drafts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='automationrun',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='volunteerhourentry',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
