# Generated by Django 6.0.7 on 2026-07-30 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_member_membershipplan_membersubscription_and_more'),
        ('events', '0003_registration_payment_status'),
        ('sites', '0004_alter_sitetheme_brand_colors'),
        ('workspace', '0006_alter_automationrule_site_alter_automationrun_site_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['site', 'kind', '-created_at'], name='ws_activity_site_kind_time'),
        ),
        migrations.AddIndex(
            model_name='aicontentdraft',
            index=models.Index(fields=['site', 'status', '-created_at'], name='ws_ai_site_status_time'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['site', 'is_active', 'trigger'], name='ws_auto_site_active_trigger'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['site', 'status', '-created_at'], name='ws_run_site_status_time'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['site', 'category', '-created_at'], name='ws_doc_site_cat_time'),
        ),
        migrations.AddIndex(
            model_name='intakeform',
            index=models.Index(fields=['site', 'is_active'], name='ws_form_site_active'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['site', 'status'], name='ws_sponsor_site_status'),
        ),
        migrations.AddIndex(
            model_name='volunteerprofile',
            index=models.Index(fields=['site', 'status'], name='ws_volunteer_site_status'),
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['site', 'status', 'due_at'], name='ws_task_site_status_due'),
        ),
    ]
