from attendance.models import AttendanceRecord
from communications.models import Campaign, CampaignRecipient, OutboundMessage
from contacts.models import Contact, Member, MemberSubscription
from content.models import BlogPost, SitePage
from events.models import (
    Event,
    EventAlbum,
    EventOccurrence,
    EventPhoto,
    Participant,
    Registration,
)
from notifications.models import Notification
from ops.models import AuditEvent
from payments.models import MembershipPayment, Order
from reviews.models import Review
from workspace.models import (
    Activity,
    AIContentDraft,
    AutomationRule,
    AutomationRun,
    Document,
    IntakeForm,
    IntakeSubmission,
    Sponsor,
    Sponsorship,
    TaskChecklistItem,
    TaskComment,
    VolunteerAssignment,
    VolunteerHourEntry,
    VolunteerProfile,
    VolunteerShift,
    WorkTask,
)


def _rows(queryset, *fields):
    return list(queryset.values(*fields))


def site_export(site):
    return {
        "format": "gather-hqs-site-export-v1",
        "site": {
            "id": site.id,
            "display_name": site.display_name,
            "slug": site.slug,
            "status": site.status,
            "timezone": site.timezone,
            "currency": site.currency,
        },
        "pages": _rows(
            SitePage.objects.for_site(site),
            "page_type",
            "title",
            "body",
            "status",
            "publish_at",
        ),
        "blog_posts": _rows(
            BlogPost.objects.for_site(site),
            "title",
            "slug",
            "excerpt",
            "body",
            "status",
            "publish_at",
        ),
        "contacts": _rows(
            Contact.objects.for_site(site),
            "id",
            "first_name",
            "last_name",
            "email",
            "phone",
            "notes",
            "email_consent_status",
            "sms_consent_status",
            "archived_at",
        ),
        "members": _rows(
            Member.objects.for_site(site),
            "contact_id",
            "administrative_status",
            "starts_on",
            "ends_on",
            "notes",
        ),
        "member_subscriptions": _rows(
            MemberSubscription.objects.for_site(site),
            "member_id",
            "plan_id",
            "status",
            "current_period_starts_at",
            "current_period_ends_at",
            "cancel_at_period_end",
        ),
        "events": _rows(
            Event.objects.for_site(site),
            "id",
            "title",
            "slug",
            "description",
            "featured_image",
            "visibility",
            "status",
            "recurrence",
        ),
        "occurrences": _rows(
            EventOccurrence.objects.for_site(site),
            "id",
            "event_id",
            "starts_at",
            "ends_at",
            "timezone",
            "venue_name",
            "venue_address",
            "capacity",
            "status",
        ),
        "event_albums": _rows(
            EventAlbum.objects.for_site(site),
            "id",
            "occurrence_id",
            "title",
            "slug",
            "description",
            "status",
            "cover_photo_id",
            "published_at",
            "created_by_id",
        ),
        "event_photos": _rows(
            EventPhoto.objects.for_site(site),
            "id",
            "album_id",
            "image",
            "caption",
            "alt_text",
            "position",
            "uploaded_by_id",
        ),
        "registrations": _rows(
            Registration.objects.for_site(site),
            "id",
            "occurrence_id",
            "contact_id",
            "response",
            "source",
            "payment_status",
            "responded_at",
        ),
        "participants": _rows(
            Participant.objects.for_site(site),
            "id",
            "registration_id",
            "first_name",
            "last_name",
            "email",
            "phone",
            "is_primary",
            "status",
        ),
        "attendance_history": _rows(
            AttendanceRecord.objects.for_site(site),
            "participant_id",
            "occurrence_id",
            "action",
            "note",
            "recorded_at",
        ),
        "orders": _rows(
            Order.objects.for_site(site),
            "id",
            "occurrence_id",
            "registration_id",
            "currency",
            "total_cents",
            "refunded_cents",
            "application_fee_bps",
            "application_fee_cents",
            "application_fee_refunded_cents",
            "stripe_fee_cents",
            "stripe_net_cents",
            "status",
            "paid_at",
        ),
        "membership_payments": _rows(
            MembershipPayment.objects.for_site(site),
            "member_subscription_id",
            "amount_due_cents",
            "amount_paid_cents",
            "currency",
            "status",
            "paid_at",
        ),
        "campaigns": _rows(
            Campaign.objects.for_site(site),
            "id",
            "name",
            "channel",
            "status",
            "subject",
            "body",
            "audience",
            "audience_tag_id",
            "audience_occurrence_id",
            "response_filter",
            "scheduled_for",
            "started_at",
            "completed_at",
            "recipient_count",
            "eligible_count",
            "excluded_count",
            "last_error",
        ),
        "campaign_recipients": _rows(
            CampaignRecipient.objects.for_site(site),
            "campaign_id",
            "contact_id",
            "address",
            "status",
            "exclusion_reason",
            "sent_at",
            "delivered_at",
            "opened_at",
            "clicked_at",
            "unsubscribed_at",
            "last_event_at",
            "last_error",
        ),
        "outbound_messages": _rows(
            OutboundMessage.objects.for_site(site),
            "id",
            "channel",
            "contact_id",
            "campaign_id",
            "kind",
            "recipient_email",
            "recipient_phone",
            "subject",
            "status",
            "attempts",
            "sent_at",
            "last_error",
            "provider",
            "provider_message_id",
            "delivered_at",
            "opened_at",
            "clicked_at",
            "unsubscribed_at",
        ),
        "notifications": _rows(
            Notification.objects.filter(site=site),
            "id",
            "recipient_id",
            "kind",
            "title",
            "message",
            "action_url",
            "read_at",
            "created_at",
        ),
        "work_tasks": _rows(
            WorkTask.objects.for_site(site),
            "id",
            "title",
            "description",
            "event_id",
            "assignee_id",
            "created_by_id",
            "status",
            "priority",
            "due_at",
            "completed_at",
        ),
        "task_checklist_items": _rows(
            TaskChecklistItem.objects.filter(task__site=site),
            "task_id",
            "text",
            "is_complete",
            "position",
            "created_at",
        ),
        "task_comments": _rows(
            TaskComment.objects.filter(task__site=site),
            "task_id",
            "author_id",
            "body",
            "created_at",
        ),
        "documents": _rows(
            Document.objects.for_site(site),
            "id",
            "title",
            "description",
            "category",
            "visibility",
            "file",
            "event_id",
            "contact_id",
            "task_id",
            "uploaded_by_id",
            "created_at",
        ),
        "volunteers": _rows(
            VolunteerProfile.objects.for_site(site),
            "id",
            "contact_id",
            "status",
            "skills",
            "availability",
            "emergency_contact",
            "emergency_phone",
            "background_check_expires_on",
            "notes",
        ),
        "volunteer_shifts": _rows(
            VolunteerShift.objects.for_site(site),
            "id",
            "title",
            "event_id",
            "starts_at",
            "ends_at",
            "location",
            "capacity",
            "instructions",
        ),
        "volunteer_assignments": _rows(
            VolunteerAssignment.objects.filter(shift__site=site),
            "shift_id",
            "volunteer_id",
            "status",
            "notes",
            "created_at",
        ),
        "volunteer_hours": _rows(
            VolunteerHourEntry.objects.for_site(site),
            "volunteer_id",
            "assignment_id",
            "service_date",
            "hours",
            "description",
            "approved_by_id",
        ),
        "sponsors": _rows(
            Sponsor.objects.for_site(site),
            "id",
            "name",
            "contact_name",
            "email",
            "phone",
            "website",
            "logo",
            "status",
            "notes",
        ),
        "sponsorships": _rows(
            Sponsorship.objects.for_site(site),
            "sponsor_id",
            "event_id",
            "level",
            "amount_cents",
            "status",
            "starts_on",
            "ends_on",
            "benefits",
            "invoice_reference",
        ),
        "intake_forms": _rows(
            IntakeForm.objects.for_site(site),
            "id",
            "title",
            "slug",
            "kind",
            "introduction",
            "confirmation_message",
            "event_id",
            "fields",
            "require_signature",
            "agreement_text",
            "create_or_update_contact",
            "is_active",
            "closes_at",
        ),
        "intake_submissions": _rows(
            IntakeSubmission.objects.for_site(site),
            "id",
            "intake_form_id",
            "contact_id",
            "response_data",
            "submitter_name",
            "submitter_email",
            "signature_name",
            "agreed_at",
            "source_ip",
            "user_agent",
            "created_at",
        ),
        "automation_rules": _rows(
            AutomationRule.objects.for_site(site),
            "id",
            "name",
            "description",
            "trigger",
            "action",
            "trigger_config",
            "action_config",
            "is_active",
            "last_run_at",
            "created_by_id",
        ),
        "automation_runs": _rows(
            AutomationRun.objects.for_site(site),
            "rule_id",
            "status",
            "trigger_data",
            "result_detail",
            "error_detail",
            "created_at",
        ),
        "ai_content_drafts": _rows(
            AIContentDraft.objects.for_site(site),
            "id",
            "content_type",
            "title",
            "instructions",
            "context",
            "output",
            "status",
            "provider",
            "model_name",
            "error_message",
            "created_by_id",
            "created_at",
        ),
        "activity": _rows(
            Activity.objects.for_site(site),
            "actor_id",
            "verb",
            "detail",
            "kind",
            "target_url",
            "created_at",
        ),
        "audit_history": _rows(
            AuditEvent.objects.filter(site_id=site.id),
            "actor_id",
            "request_id",
            "action",
            "target_type",
            "target_id",
            "summary",
            "ip_address",
            "user_agent",
            "created_at",
        ),
        "reviews": _rows(
            Review.objects.for_site(site),
            "occurrence_id",
            "participant_id",
            "display_name",
            "rating",
            "comment",
            "submitted_at",
            "edited_at",
            "deleted_at",
            "moderation_status",
            "response",
            "responded_at",
        ),
    }
