from attendance.models import AttendanceRecord
from contacts.models import Contact, Member, MemberSubscription
from content.models import BlogPost, SitePage
from events.models import Event, EventOccurrence, Participant, Registration
from payments.models import MembershipPayment, Order
from reviews.models import Review


def _rows(queryset, *fields):
    return list(queryset.values(*fields))


def site_export(site):
    return {
        "format": "gather-hqs-site-export-v1",
        "site": {
            "id": site.id,
            "display_name": site.display_name,
            "slug": site.slug,
            "status": site.status,
            "timezone": site.timezone,
            "currency": site.currency,
        },
        "pages": _rows(
            SitePage.objects.for_site(site),
            "page_type",
            "title",
            "body",
            "status",
            "publish_at",
        ),
        "blog_posts": _rows(
            BlogPost.objects.for_site(site),
            "title",
            "slug",
            "excerpt",
            "body",
            "status",
            "publish_at",
        ),
        "contacts": _rows(
            Contact.objects.for_site(site),
            "id",
            "first_name",
            "last_name",
            "email",
            "phone",
            "notes",
            "email_consent_status",
            "sms_consent_status",
            "archived_at",
        ),
        "members": _rows(
            Member.objects.for_site(site),
            "contact_id",
            "administrative_status",
            "starts_on",
            "ends_on",
            "notes",
        ),
        "member_subscriptions": _rows(
            MemberSubscription.objects.for_site(site),
            "member_id",
            "plan_id",
            "status",
            "current_period_starts_at",
            "current_period_ends_at",
            "cancel_at_period_end",
        ),
        "events": _rows(
            Event.objects.for_site(site),
            "id",
            "title",
            "slug",
            "description",
            "visibility",
            "status",
            "recurrence",
        ),
        "occurrences": _rows(
            EventOccurrence.objects.for_site(site),
            "id",
            "event_id",
            "starts_at",
            "ends_at",
            "timezone",
            "venue_name",
            "venue_address",
            "capacity",
            "status",
        ),
        "registrations": _rows(
            Registration.objects.for_site(site),
            "id",
            "occurrence_id",
            "contact_id",
            "response",
            "source",
            "payment_status",
            "responded_at",
        ),
        "participants": _rows(
            Participant.objects.for_site(site),
            "id",
            "registration_id",
            "first_name",
            "last_name",
            "email",
            "phone",
            "is_primary",
            "status",
        ),
        "attendance_history": _rows(
            AttendanceRecord.objects.for_site(site),
            "participant_id",
            "occurrence_id",
            "action",
            "note",
            "recorded_at",
        ),
        "orders": _rows(
            Order.objects.for_site(site),
            "id",
            "occurrence_id",
            "registration_id",
            "currency",
            "total_cents",
            "refunded_cents",
            "stripe_fee_cents",
            "stripe_net_cents",
            "status",
            "paid_at",
        ),
        "membership_payments": _rows(
            MembershipPayment.objects.for_site(site),
            "member_subscription_id",
            "amount_due_cents",
            "amount_paid_cents",
            "currency",
            "status",
            "paid_at",
        ),
        "reviews": _rows(
            Review.objects.for_site(site),
            "occurrence_id",
            "participant_id",
            "display_name",
            "rating",
            "comment",
            "submitted_at",
            "edited_at",
            "deleted_at",
            "moderation_status",
            "response",
            "responded_at",
        ),
    }
