# Generated by Django 6.0.3 on 2026-07-28 18:07

import django.core.validators
import django.db.models.deletion
import sites.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=160)),
                ('slug', models.SlugField(help_text="Used in the site's platform subdomain.", max_length=63, unique=True, validators=[sites.validators.validate_site_slug])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('trialing', 'Trialing'), ('active', 'Active'), ('grace', 'Payment grace period'), ('suspended', 'Suspended'), ('canceled', 'Canceled'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('timezone', models.CharField(default='America/New_York', max_length=64, validators=[sites.validators.validate_timezone])),
                ('currency', models.CharField(default='usd', max_length=3, validators=[sites.validators.validate_currency])),
                ('template_key', models.CharField(default='classic', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, upload_to='site-logos/%Y/%m/')),
                ('primary_color', models.CharField(default='#0D6EFD', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a six-digit hexadecimal color such as #336699.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(default='#6C757D', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a six-digit hexadecimal color such as #336699.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('typography_key', models.CharField(default='system', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('kind', models.CharField(choices=[('platform', 'Platform subdomain'), ('custom', 'Custom domain')], default='platform', max_length=20)),
                ('is_canonical', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_canonical', True)), fields=('site',), name='sites_one_canonical_domain')],
            },
        ),
        migrations.CreateModel(
            name='SiteRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('subscriber_admin', 'Subscriber admin'), ('site_manager', 'Site manager')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_roles_invited', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'user'), name='sites_one_role_per_user'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'subscriber_admin')), fields=('site',), name='sites_one_active_subscriber_admin')],
            },
        ),
    ]
