# Generated by Django 6.0.3 on 2026-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='template_key',
            field=models.CharField(choices=[('classic', 'Classic'), ('social', 'Social')], default='classic', max_length=50),
        ),
    ]
