# Generated by Django 6.0.3 on 2026-07-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_template_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='hero_heading',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='site-heroes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='hero_text',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site-logos/%Y/%m/'),
        ),
    ]
