# Generated by Django 6.0.7 on 2026-07-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_sitetheme_brand_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='default_refund_policy',
            field=models.TextField(blank=True, help_text='Shown to buyers before they pay and on public event pages. Individual ticket types can override it.'),
        ),
        migrations.AddField(
            model_name='site',
            name='postal_address',
            field=models.CharField(blank=True, help_text='A valid physical mailing address, required by law at the bottom of every newsletter you send. A PO box registered to your group works.', max_length=300),
        ),
    ]
