# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0005_site_business_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitetheme",
            name="show_logo_in_header",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitetheme",
            name="show_name_in_header",
            field=models.BooleanField(default=True),
        ),
    ]
