# Generated by Django 6.0.3 on 2026-07-28 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0003_sitetheme_hero_heading_sitetheme_hero_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180)),
                ('excerpt', models.CharField(blank=True, max_length=400)),
                ('body', models.TextField()),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/%Y/%m/')),
                ('author_display_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'ordering': ('-publish_at', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='content_unique_blog_slug_per_site'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'scheduled'), _negated=True), ('publish_at__isnull', False), _connector='OR'), name='content_scheduled_post_has_publish_at')],
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('newsletter', 'Newsletter')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('navigation_label', models.CharField(max_length=40)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'ordering': ('page_type',),
                'constraints': [models.UniqueConstraint(fields=('site', 'page_type'), name='content_one_page_type_per_site')],
            },
        ),
    ]
