# Generated by Django 6.0.7 on 2026-08-02

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_legacy_sections(apps, schema_editor):
    SitePage = apps.get_model("content", "SitePage")
    PageSection = apps.get_model("content", "PageSection")

    sections = []
    for page in SitePage.objects.all().iterator():
        body = (page.body or "").strip()
        if not body:
            continue
        sections.append(
            PageSection(
                id=uuid.uuid4(),
                site_id=page.site_id,
                page_id=page.id,
                section_type="content",
                position=1,
                is_enabled=True,
                is_legacy_body=True,
                heading=page.title,
                rich_text=body,
            )
        )
    if sections:
        PageSection.objects.bulk_create(sections)


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("content", "Content"),
                            ("strip", "Logo or photo strip"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=1)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_legacy_body", models.BooleanField(default=False)),
                ("heading", models.CharField(blank=True, max_length=180)),
                ("subheading", models.CharField(blank=True, max_length=320)),
                ("rich_text", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="page-sections/%Y/%m/"),
                ),
                (
                    "image_alignment",
                    models.CharField(
                        choices=[("left", "Image left"), ("right", "Image right")],
                        default="right",
                        max_length=10,
                    ),
                ),
                ("button_text", models.CharField(blank=True, max_length=40)),
                ("button_url", models.URLField(blank=True, max_length=500)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="content.sitepage",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "created_at"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 1)),
                        name="content_page_section_position_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PageSectionImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(upload_to="page-sections/%Y/%m/"),
                ),
                ("alt_text", models.CharField(max_length=180)),
                ("position", models.PositiveIntegerField(default=1)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.pagesection",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "created_at"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 1)),
                        name="content_page_section_image_position_positive",
                    )
                ],
            },
        ),
        migrations.RunPython(create_legacy_sections, migrations.RunPython.noop),
    ]
