# Generated by Django 6.0.3 on 2026-07-28 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('events', '0002_event_max_guests_invitation_registration_participant_and_more'),
        ('sites', '0003_sitetheme_hero_heading_sitetheme_hero_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_history', to='events.participant'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddField(
            model_name='attendancestatus',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_check_ins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancestatus',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_status', to='events.participant'),
        ),
        migrations.AddField(
            model_name='attendancestatus',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
